### ISSUE TITLE
Feature suggestion import/export

### ISSUE THREAD

**Issue by mediageni** [pschlan/cron-job.org#17] opened 2017-08-05 15:30 UTC
Hi, I've created several jobs, would there be a way to export my cron jobs?

I'm going to install it on my own server so it would be nice to import all my cron jobs.

Is there going to be an import/export function in the future?

thanks

**Comment by pschlan** [comment] 2020-03-29 15:54
Duplicate of #20

**Closed by pschlan** 2020-03-29 15:54 UTC
