### ISSUE TITLE
Is there a way to trigger a specific cron job immediately for testing purposes?

### ISSUE THREAD

**Issue by cbdeveloper** [pschlan/cron-job.org#76] opened 2021-06-01 08:18 UTC
Thank you for this awesome tool. This could turn into a feature request.

Is there a way to trigger a cron job immediately for testing purposes?

I know I can always use Postman, but this would be easier to set up.

Currently, I don't see it or I haven't found that option yet.

![image](https://user-images.githubusercontent.com/43407798/120290326-25464580-c2ba-11eb-8721-09337cde25d4.png)

**Comment by pschlan** [comment] 2021-08-19 06:23
That's a nice idea, but it might be problematic from a security point of view, since a real time API to trigger requests opens up the possibility to abuse the service as a proxy. I'll think about it - maybe this can be mitigated.

**Comment by pschlan** [comment] 2021-08-29 14:21
Closing as duplicate of #14

**Closed by pschlan** 2021-08-29 14:21 UTC
