### ISSUE TITLE
HTML files

### ISSUE THREAD

**Issue by basil2style** [pschlan/cron-job.org#37] opened 2018-11-15 20:49 UTC
Hi, 
I am looking for the frontend files of the project but couldn't find it. Is it possible someone to show the file, it would be great if you can help me. Thanks

**Comment by frandelarosa** [comment] 2018-12-17 09:23
Same here, waiting for it.

**Comment by pschlan** [comment] 2019-09-19 08:51
Duplicate of issue #19. This is still on my radar.

**Closed by pschlan** 2019-09-19 08:51 UTC
